@chatId = 5bfb70bf-ec65-407c-b958-52178f08de7f

### Generate Image Upload Credentials
POST {{host}}/api/chat/{{chatId}}/images-upload
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

[
  {
    "fileName": "image1.jpg",
    "mimeType": "image/jpeg"
  }
]
